# Generated by Django 5.2 on 2025-04-25 06:22

import apps.users.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Personal_Info',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(blank=True, default='DEFAULT_IMAGES/default.jpg', null=True, upload_to=apps.users.models.user_profile_upload_path)),
                ('full_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('course', models.CharField(choices=[('bca', 'Bachelor of Computer Application'), ('ba', 'Bachelor of Arts'), ('llb', 'Bachelor of Law'), ('bsc', 'Bachelor of Science'), ('b.tech', 'Civil Engineering'), ('bhm', 'Bachelor of Hotel Management')], max_length=255)),
                ('resume', models.FileField(upload_to=apps.users.models.user_resume_upload_path)),
                ('contact_number', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='users.user')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
